service: coldstart

provider:
  name: aws
  versionFunctions: false

functions:
  node810-memory-128:
    name: aws-coldstart-node810-128mb
    description: Cold start test
    runtime: nodejs8.10
    handler: nodejs/handler.hello
    memorySize: 128

  node810-memory-256:
    name: aws-coldstart-node810-256mb
    description: Cold start test
    runtime: nodejs8.10
    handler: nodejs/handler.hello
    memorySize: 256

  node810-memory-512:
    name: aws-coldstart-node810-512mb
    description: Cold start test
    runtime: nodejs8.10
    handler: nodejs/handler.hello
    memorySize: 512

  node810-memory-1024:
    name: aws-coldstart-node810-1024mb
    description: Cold start test
    runtime: nodejs8.10
    handler: nodejs/handler.hello
    memorySize: 1024

  node810-memory-1536:
    name: aws-coldstart-node810-1536mb
    description: Cold start test
    runtime: nodejs8.10
    handler: nodejs/handler.hello
    memorySize: 1536