service: memstress

provider:
  name: azure
  location: East US

plugins:
  - serverless-azure-functions

functions:
  memstress:
    handler: nodejs/handler.handler
    name: memstress
    description: "a memory intensive function"
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
      - http: true
        x-azure-settings:
          direction: out
