service: iostress

provider:
  name: azure
  location: East US

plugins:
  - serverless-azure-functions

functions:
  iostress:
    handler: nodejs/handler.handler
    name: iostress
    description: "io intensive function"
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: $return
